### ISSUE TITLE
Sorting Error

### ISSUE THREAD

**Issue by Ashrayel** [ChobitsCrazy/BetterSorting#67]
Since your last update, for some reason Carpentry 1 is now being sorted to the bottom of my skill literature.  I generally use sort by category and have never had any issues before.  Just wanted to let you know.  Thanks!

**Comment by Aurani** [comment]
+1, this is due to a missing space between the 1 and the period in "Vol. 1".

**Comment by Franisz** [comment]
I don't know why but literature item names got removed in https://github.com/ChobitsCrazy/BetterSorting/commit/fb6d7e1cb0d0a6735391bd426a70f5685171fe4a, so right now BetterSorting doesn't touch that.
Category itself for skill books is given automatically so there shouldn't be any mistake. Not sure if the issue is reffering to item name or item category so please provide a screenshot.

**Comment by Aurani** [comment]
I literally said what the issue was, but here you go.
![image_2023-07-06_112609533](https://github.com/ChobitsCrazy/BetterSorting/assets/13284814/9176667f-3dec-43fc-a5a2-0de2b418d66c)

**Comment by Franisz** [comment]
> I don't know why but literature item names got removed in https://github.com/ChobitsCrazy/BetterSorting/commit/fb6d7e1cb0d0a6735391bd426a70f5685171fe4a, so right now BetterSorting doesn't touch that.

So this isn't caused by BetterSorting. And you can see that BetterSorting used `Beginner` instead of `For Dummies` in tier 1 books [ItemName_EN](https://github.com/ChobitsCrazy/BetterSorting/blob/fb6d7e1cb0d0a6735391bd426a70f5685171fe4a/media/lua/shared/Translate/EN/ItemName_EN.txt)

**Comment by ChobitsCrazy** [comment]
Yes originally I only updated the names for Build40 since they still used the old naming convention. Currently in Vanilla the books all already have the volume numbers so renaming them is redundant to core. However your screenshot shows "For Dummies" which my mod has never had, so this is an issue with another mod. (IndieStone found "For Dummies" offensive at some point during B41 so it was removed) I however did notice that my mod still shows other names so I will fix that for the next update.
